-- Migration 0001: Core Entities
-- Tables: users, propedeutic_lines, programs, student_outcomes

-- IMPORTANT: users.id references auth.users.id from Supabase Auth
-- The users table extends Supabase Auth with app-specific fields

CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'leader', 'teacher')),
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'local' CHECK (auth_provider IN ('local', 'microsoft')),
    microsoft_oid VARCHAR(255) UNIQUE,
    pege_id VARCHAR(50) UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_users_microsoft_oid ON users(microsoft_oid) WHERE microsoft_oid IS NOT NULL;
CREATE UNIQUE INDEX idx_users_pege_id ON users(pege_id) WHERE pege_id IS NOT NULL;

CREATE TABLE public.propedeutic_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE public.programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propedeutic_line_id BIGINT NOT NULL REFERENCES public.propedeutic_lines(id),
    name VARCHAR(200) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    cycle_level VARCHAR(20) NOT NULL CHECK (cycle_level IN ('tecnico', 'tecnologico', 'profesional')),
    faculty VARCHAR(200),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_programs_line ON public.programs(propedeutic_line_id);
CREATE INDEX idx_programs_cycle ON public.programs(cycle_level);

CREATE TABLE public.student_outcomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    program_id BIGINT REFERENCES public.programs(id)
);

CREATE INDEX idx_so_program ON public.student_outcomes(program_id);
