-- Migration 0002: Assessment Framework
-- Tables: periods, rubrics, perf_indicators, pi_levels, level_thresholds

CREATE TABLE public.periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    student_outcome_id BIGINT NOT NULL REFERENCES public.student_outcomes(id),
    rubric_id BIGINT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'open', 'closed')),
    created_by UUID NOT NULL REFERENCES public.users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_periods_so ON public.periods(student_outcome_id);
CREATE INDEX idx_periods_status ON public.periods(status);

CREATE TABLE public.rubrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_outcome_id BIGINT NOT NULL REFERENCES public.student_outcomes(id),
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    cloned_from BIGINT REFERENCES public.rubrics(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.perf_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubric_id BIGINT NOT NULL REFERENCES public.rubrics(id) ON DELETE CASCADE,
    code VARCHAR(10) NOT NULL,
    description TEXT NOT NULL,
    pi_weight NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (pi_weight >= 0 AND pi_weight <= 100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    position INT NOT NULL,
    UNIQUE(rubric_id, code)
);

CREATE INDEX idx_pi_rubric ON public.perf_indicators(rubric_id);

CREATE TABLE public.pi_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id) ON DELETE CASCADE,
    level_value INT NOT NULL CHECK (level_value BETWEEN 1 AND 4),
    label VARCHAR(20) NOT NULL CHECK (label IN ('Poor', 'Inadequate', 'Adequate', 'Exemplary')),
    descriptor TEXT NOT NULL,
    UNIQUE(perf_indicator_id, level_value)
);

CREATE TABLE public.level_thresholds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubric_id BIGINT NOT NULL REFERENCES public.rubrics(id) UNIQUE,
    poor_max NUMERIC(4,2) NOT NULL DEFAULT 2.00,
    inadequate_max NUMERIC(4,2) NOT NULL DEFAULT 3.00,
    adequate_max NUMERIC(4,2) NOT NULL DEFAULT 4.00
);

-- FK from periods.rubric_id -> rubrics.id (added after both tables exist)
ALTER TABLE public.periods ADD CONSTRAINT fk_periods_rubric 
    FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id);
