-- Migration 0003: Modules and Students
-- Tables: modules, module_staff, students, module_students, student_exclusions

CREATE TABLE public.modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    course_code VARCHAR(30) NOT NULL,
    course_name VARCHAR(200) NOT NULL,
    group_name VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed')),
    submitted_at TIMESTAMPTZ
);

CREATE INDEX idx_modules_period ON public.modules(period_id);
CREATE INDEX idx_modules_period_status ON public.modules(period_id, status);

CREATE TABLE public.module_staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id),
    UNIQUE(module_id, user_id)
);

CREATE INDEX idx_module_staff_user ON public.module_staff(user_id);

CREATE TABLE public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_id VARCHAR(20) NOT NULL UNIQUE,
    document_number VARCHAR(15) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    is_suppressed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE public.module_students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES public.students(id),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'excluded')),
    UNIQUE(module_id, student_id)
);

CREATE INDEX idx_module_students_module ON public.module_students(module_id);
CREATE INDEX idx_module_students_student ON public.module_students(student_id);

CREATE TABLE public.student_exclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_student_id BIGINT NOT NULL REFERENCES public.module_students(id),
    reason_code VARCHAR(30) NOT NULL CHECK (reason_code IN ('withdrew', 'never_attended', 'medical', 'other')),
    reason_text TEXT,
    excluded_by UUID NOT NULL REFERENCES public.users(id),
    excluded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
