-- Migration 0004: Grading
-- Tables: assessments, module_analysis

CREATE TABLE public.assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_student_id BIGINT NOT NULL REFERENCES public.module_students(id) ON DELETE CASCADE,
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id),
    level INT NOT NULL CHECK (level BETWEEN 1 AND 4),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(module_student_id, perf_indicator_id)
);

CREATE INDEX idx_assessments_module_student ON public.assessments(module_student_id);

CREATE TABLE public.module_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE,
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id),
    analysis_text TEXT NOT NULL CHECK (char_length(analysis_text) <= 2000),
    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(module_id, perf_indicator_id)
);
