-- Migration 0005: Leader Features
-- Tables: leader_analysis, action_plans, reports, reminder_log, leader_report_drafts

CREATE TABLE public.leader_analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id),
    analysis_text TEXT NOT NULL,
    updated_by UUID NOT NULL REFERENCES public.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(period_id, perf_indicator_id)
);

CREATE TABLE public.action_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id),
    action_type VARCHAR(20) NOT NULL CHECK (action_type IN ('corrective', 'preventive', 'improvement')),
    description TEXT NOT NULL CHECK (char_length(description) <= 2000),
    responsible VARCHAR(200) NOT NULL,
    estimated_date VARCHAR(20) NOT NULL,
    implemented BOOLEAN NOT NULL DEFAULT FALSE,
    updated_by UUID NOT NULL REFERENCES public.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(period_id, perf_indicator_id)
);

CREATE TABLE public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    format VARCHAR(10) NOT NULL CHECK (format IN ('pdf', 'xlsx')),
    filename VARCHAR(200) NOT NULL,
    generated_by UUID NOT NULL REFERENCES public.users(id),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.reminder_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id),
    sent_by UUID NOT NULL REFERENCES public.users(id),
    recipient_ids JSONB NOT NULL,
    message_body TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.leader_report_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id) UNIQUE,
    pi_conclusions JSONB NOT NULL DEFAULT '{}',
    last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by UUID NOT NULL REFERENCES public.users(id)
);
