-- Migration 0007: Integration and Multi-Program
-- Tables: oracle_sync_log, program_memberships

CREATE TABLE public.oracle_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source VARCHAR(30) NOT NULL CHECK (source IN ('csv', 'academusoft', 'rest', 'manual')),
    periodo_codigo VARCHAR(50) NOT NULL,
    docentes_count INT NOT NULL DEFAULT 0,
    modulos_count INT NOT NULL DEFAULT 0,
    estudiantes_count INT NOT NULL DEFAULT 0,
    admin_id UUID NOT NULL REFERENCES public.users(id),
    detail JSONB
);

CREATE INDEX idx_sync_log_ts ON public.oracle_sync_log(ts);
CREATE INDEX idx_sync_log_source ON public.oracle_sync_log(source);
CREATE INDEX idx_sync_log_admin ON public.oracle_sync_log(admin_id);

CREATE TABLE public.program_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    program_id BIGINT NOT NULL REFERENCES public.programs(id) ON DELETE CASCADE,
    UNIQUE(user_id, program_id)
);

CREATE INDEX idx_pm_user ON public.program_memberships(user_id);
CREATE INDEX idx_pm_program ON public.program_memberships(program_id);
