-- Migration 0012: Measurement cycle, RA consolidator assignments, module program
-- Supports PRD v2.4 institutional mapping (MODULOS 2025-2 POR RESULTADOS DE APRENDIZAJE.xlsx)

CREATE TABLE public.measurement_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('draft', 'open', 'closed'))
);

CREATE INDEX idx_measurement_cycles_status ON public.measurement_cycles(status);

CREATE TABLE public.ra_consolidator_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES public.measurement_cycles(id) ON DELETE CASCADE,
    program_id BIGINT NOT NULL REFERENCES public.programs(id),
    student_outcome_id BIGINT NOT NULL REFERENCES public.student_outcomes(id),
    consolidator_user_id UUID NOT NULL REFERENCES public.users(id),
    UNIQUE (cycle_id, program_id, student_outcome_id)
);

CREATE INDEX idx_ra_consolidator_cycle ON public.ra_consolidator_assignments(cycle_id);
CREATE INDEX idx_ra_consolidator_program ON public.ra_consolidator_assignments(program_id);
CREATE INDEX idx_ra_consolidator_user ON public.ra_consolidator_assignments(consolidator_user_id);

ALTER TABLE public.periods
    ADD COLUMN IF NOT EXISTS cycle_id BIGINT REFERENCES public.measurement_cycles(id);

CREATE INDEX IF NOT EXISTS idx_periods_cycle ON public.periods(cycle_id);

ALTER TABLE public.modules
    ADD COLUMN IF NOT EXISTS program_id BIGINT REFERENCES public.programs(id);

CREATE INDEX IF NOT EXISTS idx_modules_program ON public.modules(program_id);

-- Default cycle for existing MVP data
INSERT INTO public.measurement_cycles (code, name, status)
VALUES ('2025-2', 'Cuatrimestre 2025-2', 'open')
ON CONFLICT (code) DO NOTHING;

UPDATE public.periods p
SET cycle_id = mc.id
FROM public.measurement_cycles mc
WHERE mc.code = '2025-2'
  AND p.cycle_id IS NULL
  AND p.name LIKE '2025-2%';

ALTER TABLE public.measurement_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ra_consolidator_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "measurement_cycles_read" ON public.measurement_cycles
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "ra_consolidator_assignments_read" ON public.ra_consolidator_assignments
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "measurement_cycles_admin_write" ON public.measurement_cycles
    FOR ALL TO authenticated
    USING (public.user_has_role('admin'))
    WITH CHECK (public.user_has_role('admin'));

CREATE POLICY "ra_consolidator_assignments_admin_write" ON public.ra_consolidator_assignments
    FOR ALL TO authenticated
    USING (public.user_has_role('admin'))
    WITH CHECK (public.user_has_role('admin'));
