-- Migration 0013: Normalize measurement model (PRD v2.4)
-- - module_ra_evaluations: asignación módulo físico × período de captura (RA)
-- - modules: solo módulo físico (ciclo + programa + código + grupo)
-- - module_analysis: alcance por evaluación, no por módulo físico
-- - leader_analysis, action_plans, leader_report_drafts: alcance programa × período

-- =============================================================================
-- 1. module_ra_evaluations
-- =============================================================================
CREATE TABLE public.module_ra_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id BIGINT NOT NULL REFERENCES public.modules(id) ON DELETE CASCADE,
    period_id BIGINT NOT NULL REFERENCES public.periods(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'in_progress', 'completed')),
    submitted_at TIMESTAMPTZ,
    UNIQUE (module_id, period_id)
);

CREATE INDEX idx_mre_module ON public.module_ra_evaluations(module_id);
CREATE INDEX idx_mre_period ON public.module_ra_evaluations(period_id);
CREATE INDEX idx_mre_period_status ON public.module_ra_evaluations(period_id, status);

INSERT INTO public.module_ra_evaluations (module_id, period_id, status, submitted_at)
SELECT id, period_id, status, submitted_at
FROM public.modules
WHERE period_id IS NOT NULL;

-- =============================================================================
-- 2. modules → módulo físico (cycle_id, sin period_id/status)
-- =============================================================================
ALTER TABLE public.modules
    ADD COLUMN IF NOT EXISTS cycle_id BIGINT REFERENCES public.measurement_cycles(id);

UPDATE public.modules m
SET cycle_id = p.cycle_id
FROM public.periods p
WHERE p.id = m.period_id AND m.cycle_id IS NULL;

UPDATE public.modules m
SET cycle_id = mc.id
FROM public.measurement_cycles mc
WHERE mc.code = '2025-2' AND m.cycle_id IS NULL;

CREATE TEMP TABLE _module_redirect AS
SELECT
    id AS old_id,
    MIN(id) OVER (
        PARTITION BY cycle_id, COALESCE(program_id, -1), course_code, group_name
    ) AS keep_id
FROM public.modules
WHERE cycle_id IS NOT NULL;

DELETE FROM _module_redirect WHERE old_id = keep_id;

UPDATE public.module_ra_evaluations mre
SET module_id = r.keep_id
FROM _module_redirect r
WHERE mre.module_id = r.old_id
  AND NOT EXISTS (
      SELECT 1 FROM public.module_ra_evaluations existing
      WHERE existing.module_id = r.keep_id AND existing.period_id = mre.period_id
  );

DELETE FROM public.module_ra_evaluations mre
USING _module_redirect r
WHERE mre.module_id = r.old_id;

INSERT INTO public.module_staff (module_id, user_id)
SELECT r.keep_id, ms.user_id
FROM public.module_staff ms
JOIN _module_redirect r ON r.old_id = ms.module_id
ON CONFLICT (module_id, user_id) DO NOTHING;

DELETE FROM public.module_staff ms
USING _module_redirect r
WHERE ms.module_id = r.old_id;

UPDATE public.module_students ms
SET module_id = r.keep_id
FROM _module_redirect r
WHERE ms.module_id = r.old_id
  AND NOT EXISTS (
      SELECT 1 FROM public.module_students existing
      WHERE existing.module_id = r.keep_id AND existing.student_id = ms.student_id
  );

DELETE FROM public.module_students ms
USING _module_redirect r
WHERE ms.module_id = r.old_id;

DELETE FROM public.modules m
USING _module_redirect r
WHERE m.id = r.old_id;

ALTER TABLE public.modules DROP COLUMN IF EXISTS period_id;
ALTER TABLE public.modules DROP COLUMN IF EXISTS status;
ALTER TABLE public.modules DROP COLUMN IF EXISTS submitted_at;

DROP INDEX IF EXISTS idx_modules_period;
DROP INDEX IF EXISTS idx_modules_period_status;

CREATE UNIQUE INDEX idx_modules_physical_unique
    ON public.modules (cycle_id, COALESCE(program_id, -1), course_code, group_name);

CREATE INDEX IF NOT EXISTS idx_modules_cycle ON public.modules(cycle_id);

ALTER TABLE public.modules
    ALTER COLUMN cycle_id SET NOT NULL;

-- =============================================================================
-- 3. module_analysis → module_ra_evaluation_id
-- =============================================================================
-- Policies must be dropped before removing module_id (they reference that column).
CREATE OR REPLACE FUNCTION public.is_evaluation_teacher(p_evaluation_id bigint)
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM public.module_ra_evaluations mre
        JOIN public.module_staff mst ON mst.module_id = mre.module_id
        WHERE mre.id = p_evaluation_id AND mst.user_id = auth.uid()
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.is_evaluation_teacher(bigint) TO authenticated;

DROP POLICY IF EXISTS "module_analysis_insert_teacher" ON public.module_analysis;
DROP POLICY IF EXISTS "module_analysis_update_teacher" ON public.module_analysis;

ALTER TABLE public.module_analysis
    ADD COLUMN IF NOT EXISTS module_ra_evaluation_id BIGINT REFERENCES public.module_ra_evaluations(id) ON DELETE CASCADE;

UPDATE public.module_analysis ma
SET module_ra_evaluation_id = mre.id
FROM public.module_ra_evaluations mre
WHERE mre.module_id = ma.module_id;

DELETE FROM public.module_analysis WHERE module_ra_evaluation_id IS NULL;

ALTER TABLE public.module_analysis
    ALTER COLUMN module_ra_evaluation_id SET NOT NULL;

ALTER TABLE public.module_analysis
    DROP CONSTRAINT IF EXISTS module_analysis_module_id_perf_indicator_id_key;

ALTER TABLE public.module_analysis DROP COLUMN module_id;

ALTER TABLE public.module_analysis
    ADD CONSTRAINT module_analysis_evaluation_pi_key
    UNIQUE (module_ra_evaluation_id, perf_indicator_id);

CREATE INDEX IF NOT EXISTS idx_module_analysis_evaluation ON public.module_analysis(module_ra_evaluation_id);

CREATE POLICY "module_analysis_insert_teacher" ON public.module_analysis
    FOR INSERT TO authenticated
    WITH CHECK (public.is_evaluation_teacher(module_ra_evaluation_id));

CREATE POLICY "module_analysis_update_teacher" ON public.module_analysis
    FOR UPDATE TO authenticated
    USING (public.is_evaluation_teacher(module_ra_evaluation_id));

-- =============================================================================
-- 4. Tablas del líder: program_id
-- =============================================================================
CREATE TEMP TABLE _period_program AS
SELECT DISTINCT ON (mre.period_id)
    mre.period_id,
    m.program_id
FROM public.module_ra_evaluations mre
JOIN public.modules m ON m.id = mre.module_id
WHERE m.program_id IS NOT NULL
ORDER BY mre.period_id, m.program_id;

ALTER TABLE public.leader_analysis
    ADD COLUMN program_id BIGINT REFERENCES public.programs(id);

UPDATE public.leader_analysis la
SET program_id = pp.program_id
FROM _period_program pp
WHERE la.period_id = pp.period_id AND la.program_id IS NULL;

DELETE FROM public.leader_analysis WHERE program_id IS NULL;

ALTER TABLE public.leader_analysis
    DROP CONSTRAINT IF EXISTS leader_analysis_period_id_perf_indicator_id_key;

ALTER TABLE public.leader_analysis
    ALTER COLUMN program_id SET NOT NULL;

ALTER TABLE public.leader_analysis
    ADD CONSTRAINT leader_analysis_period_program_pi_key
    UNIQUE (period_id, program_id, perf_indicator_id);

CREATE INDEX idx_leader_analysis_program ON public.leader_analysis(program_id);

ALTER TABLE public.action_plans
    ADD COLUMN program_id BIGINT REFERENCES public.programs(id);

UPDATE public.action_plans ap
SET program_id = pp.program_id
FROM _period_program pp
WHERE ap.period_id = pp.period_id AND ap.program_id IS NULL;

DELETE FROM public.action_plans WHERE program_id IS NULL;

ALTER TABLE public.action_plans
    DROP CONSTRAINT IF EXISTS action_plans_period_id_perf_indicator_id_key;

ALTER TABLE public.action_plans
    ALTER COLUMN program_id SET NOT NULL;

ALTER TABLE public.action_plans
    ADD CONSTRAINT action_plans_period_program_pi_key
    UNIQUE (period_id, program_id, perf_indicator_id);

CREATE INDEX idx_action_plans_program ON public.action_plans(program_id);

DROP POLICY IF EXISTS "leader_report_drafts_insert_admin_leader" ON public.leader_report_drafts;
DROP POLICY IF EXISTS "leader_report_drafts_update_admin_leader" ON public.leader_report_drafts;
DROP POLICY IF EXISTS "leader_report_drafts_read" ON public.leader_report_drafts;

ALTER TABLE public.leader_report_drafts RENAME TO leader_report_drafts_legacy;

CREATE TABLE public.leader_report_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL REFERENCES public.periods(id) ON DELETE CASCADE,
    program_id BIGINT NOT NULL REFERENCES public.programs(id),
    perf_indicator_id BIGINT NOT NULL REFERENCES public.perf_indicators(id),
    conclusion_text TEXT NOT NULL DEFAULT '' CHECK (char_length(conclusion_text) <= 3000),
    updated_by UUID NOT NULL REFERENCES public.users(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (period_id, program_id, perf_indicator_id)
);

CREATE INDEX idx_leader_report_drafts_period ON public.leader_report_drafts(period_id);
CREATE INDEX idx_leader_report_drafts_program ON public.leader_report_drafts(program_id);

INSERT INTO public.leader_report_drafts (
    period_id, program_id, perf_indicator_id, conclusion_text, updated_by, updated_at
)
SELECT
    l.period_id,
    pp.program_id,
    (kv.key)::bigint,
    kv.value,
    l.updated_by,
    l.last_updated
FROM public.leader_report_drafts_legacy l
JOIN _period_program pp ON pp.period_id = l.period_id
CROSS JOIN LATERAL jsonb_each_text(l.pi_conclusions) AS kv(key, value)
WHERE kv.key ~ '^\d+$';

DROP TABLE public.leader_report_drafts_legacy;

-- =============================================================================
-- 5. RLS y funciones auxiliares
-- =============================================================================
ALTER TABLE public.module_ra_evaluations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "module_ra_evaluations_read" ON public.module_ra_evaluations
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "module_ra_evaluations_insert_admin_leader" ON public.module_ra_evaluations
    FOR INSERT TO authenticated
    WITH CHECK (public.user_has_role('admin') OR public.user_has_role('leader'));

CREATE POLICY "module_ra_evaluations_update" ON public.module_ra_evaluations
    FOR UPDATE TO authenticated
    USING (
        public.user_has_role('admin')
        OR public.user_has_role('leader')
        OR public.is_module_teacher(module_id)
    );

CREATE OR REPLACE FUNCTION public.is_program_consolidator(p_program_id bigint, p_period_id bigint)
RETURNS boolean AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1
        FROM public.ra_consolidator_assignments rca
        JOIN public.periods p ON p.id = p_period_id
        WHERE rca.program_id = p_program_id
          AND rca.student_outcome_id = p.student_outcome_id
          AND rca.consolidator_user_id = auth.uid()
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.is_program_consolidator(bigint, bigint) TO authenticated;

DROP POLICY IF EXISTS "leader_analysis_insert_admin_leader" ON public.leader_analysis;
DROP POLICY IF EXISTS "leader_analysis_update_admin_leader" ON public.leader_analysis;

CREATE POLICY "leader_analysis_write" ON public.leader_analysis
    FOR INSERT TO authenticated
    WITH CHECK (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

CREATE POLICY "leader_analysis_update" ON public.leader_analysis
    FOR UPDATE TO authenticated
    USING (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

DROP POLICY IF EXISTS "action_plans_insert_admin_leader" ON public.action_plans;
DROP POLICY IF EXISTS "action_plans_update_admin_leader" ON public.action_plans;

CREATE POLICY "action_plans_write" ON public.action_plans
    FOR INSERT TO authenticated
    WITH CHECK (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

CREATE POLICY "action_plans_update" ON public.action_plans
    FOR UPDATE TO authenticated
    USING (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

CREATE POLICY "leader_report_drafts_write" ON public.leader_report_drafts
    FOR INSERT TO authenticated
    WITH CHECK (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

CREATE POLICY "leader_report_drafts_update" ON public.leader_report_drafts
    FOR UPDATE TO authenticated
    USING (
        public.user_has_role('admin')
        OR public.is_program_consolidator(program_id, period_id)
    );

ALTER TABLE public.leader_report_drafts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "leader_report_drafts_read" ON public.leader_report_drafts
    FOR SELECT TO authenticated USING (true);
