-- Pesos de PI por asignación módulo×RA (docente, fila 12 del Excel EF_ASESSM_SO_GENERIC)
-- y corrección de rúbrica RA3 con descriptores reales (sustituye placeholders del seed).

CREATE TABLE public.module_ra_evaluation_pi_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_ra_evaluation_id BIGINT NOT NULL
        REFERENCES public.module_ra_evaluations(id) ON DELETE CASCADE,
    perf_indicator_id BIGINT NOT NULL
        REFERENCES public.perf_indicators(id) ON DELETE CASCADE,
    pi_weight NUMERIC(5, 2) NOT NULL
        CHECK (pi_weight >= 0 AND pi_weight <= 100),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (module_ra_evaluation_id, perf_indicator_id)
);

CREATE INDEX idx_mrepw_evaluation
    ON public.module_ra_evaluation_pi_weights(module_ra_evaluation_id);

ALTER TABLE public.module_ra_evaluation_pi_weights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "mrepw_read" ON public.module_ra_evaluation_pi_weights
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "mrepw_insert_teacher" ON public.module_ra_evaluation_pi_weights
    FOR INSERT TO authenticated
    WITH CHECK (public.is_evaluation_teacher(module_ra_evaluation_id));

CREATE POLICY "mrepw_update_teacher" ON public.module_ra_evaluation_pi_weights
    FOR UPDATE TO authenticated
    USING (public.is_evaluation_teacher(module_ra_evaluation_id));

-- Rúbrica RA3 (rubric_id = 3): descripciones y descriptores alineados al dominio real
-- (misma estructura que la rúbrica importada con datos de análisis documental).
UPDATE public.perf_indicators dest
SET description = src.description
FROM public.perf_indicators src
WHERE dest.rubric_id = 3
  AND src.rubric_id = 1
  AND dest.position = src.position
  AND dest.is_active
  AND src.is_active;

UPDATE public.pi_levels dest_pl
SET
    descriptor = src_pl.descriptor,
    label = src_pl.label
FROM public.perf_indicators dest_pi
JOIN public.perf_indicators src_pi
    ON src_pi.rubric_id = 1
    AND src_pi.position = dest_pi.position
    AND src_pi.is_active
JOIN public.pi_levels src_pl
    ON src_pl.perf_indicator_id = src_pi.id
WHERE dest_pi.rubric_id = 3
  AND dest_pi.is_active
  AND dest_pl.perf_indicator_id = dest_pi.id
  AND dest_pl.level_value = src_pl.level_value;
